/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package daggerok

import spock.lang.Specification

class Tests extends Specification {
    def 'application has a greeting'() {
        when:
        def result = new Random().nextInt(100)
        then:
        result <= 100
    }
}
